{{- define "common-template.service" }}
  {{- if .Values.configmap.enabled -}}
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ include "common-template.fullname" . }}-cm
    labels:
      {{- include "common-template.labels" . | nindent 4 }}
  data:
    {{- range $name, $config := .Values.configmap.values }}
    {{ $name }}: {{ $config | quote }}
    {{- end }}
  {{- end }}
{{- end }}
