# nameOverride: auth
replicaCount: 1
image:
  repository: haeseung/nginx
  tag: 1.28-perl-test # 변경 감지 테스트시 1.29-perl
  pullPolicy: IfNotPresent
# configmap:
#   enabled: true
#   values:
#     SPRING_PROFILES_ACTIVE: dev-new
#     config_host: cm-config-rollout-active-svc.cm-dev # configmap
rollout:
  strategy:
    blueGreen:
      autoPromotionEnabled: true
# envFrom:
#   - secretRef:
#       name: config-key-scr
secrets:
  enabled: false